export enum ActionTypes {
  SET_TOKEN = "SET_TOKEN",
  SET_SESSIONS = "SET_SESSIONS",
  SET_ERROR = "SET_ERROR",
  ADD_SESSION = "ADD_SESSION",
  SET_PERSONAL_INFO = "SET_PERSONAL_INFO",
  LOGOUT = "LOGOUT",
  UPDATE_SESSION = "UPDATE_SESSION",
  REMOVE_SESSION = "REMOVE_SESSION",
}
